# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-31 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('vendor_email', models.EmailField(max_length=30)),
                ('vendor_phone', models.IntegerField()),
                ('vendor_bio', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('todays_location', models.CharField(max_length=110)),
                ('todays_hours', models.CharField(max_length=110)),
                ('serving_today', models.TextField()),
                ('truck_service', models.BooleanField(default=True)),
                ('cart_service', models.BooleanField(default=False)),
                ('popup_service', models.BooleanField(default=False)),
            ],
        ),
    ]
