# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-31 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlisting',
            name='todays_hours',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vendorlisting',
            name='todays_location',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vendorlisting',
            name='vendor_bio',
            field=models.CharField(max_length=50),
        ),
    ]
