# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-31 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170331_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlisting',
            name='vendor_image',
        ),
    ]
